#!/usr/bin/env bash
# This script displays a list of currently running processes in a user-oriented format with process hierarchy.

# Use ps to display all processes in a user-oriented format with process hierarchy
ps aux --forest | awk '{printf "%-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s %-10s\n", $1, $2, $3, $4, $5, $6, $7, $8, $9, $10}' | head -50
