#!/usr/bin/env bash
# This script displays fun messages when receiving signals

# Get the PID of the current script and store it in the file
echo $$ > /var/run/myscript.pid
trap 'echo "I hate the kill command"; rm -rf /var/run/myscript.pid; exit'' SIGTERM
trap 'echo "Y U no love me?!"' SIGINT
trap 'rm -f /var/run/myscript.pid; exit' SIGQUIT SIGTERM

# Display "To infinity and beyond" indefinitely
while true; do
    echo "To infinity and beyond"
    sleep 2
done
