#!/usr/bin/env bash
# This script stops the 4-to_infinity_and_beyond process.

# Find the PID of the 4-to_infinity_and_beyond process
pid=$(pgrep -f "4-to_infinity_and_beyond")

# If the process is running, terminate it
if [ -n "$pid" ]; then
    pkill -TERM -f "4-to_infinity_and_beyond"
    echo "Process stopped"
else
    echo "Process 4-to_infinity_and_beyond is not running"
fi