#!/usr/bin/env bash
# Bash script to configure an Ubuntu server

# Create a backup of the hosts file
cp /etc/hosts ~/hosts.new

# Modify the hosts file to configure localhost and facebook.com
sed -i 's/^127\.0\.0\.1\slocalhost/127.0.0.2 localhost/' ~/hosts.new
sed -i 's/^.*facebook.com/8.8.8.8 facebook.com/' ~/hosts.new

# Replace the original hosts file with the modified one
cp -f ~/hosts.new /etc/hosts

# Display success message
echo "Configuration complete"