#!/usr/bin/env bash
# Script to display all active IPv4 IPs on the machine

# Retrieve all IPv4 addresses associated with active network interfaces
ipv4_addresses=$(ip -4 addr show | grep inet | awk '{print $2}' | cut -d '/' -f1)

# Print each IPv4 address
echo "$ipv4_addresses"